ALTER TABLE items ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
--;;
ALTER TABLE lists ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
--;;
ALTER TABLE user_lists ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
--;;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
